# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c3974eb8a62cb5e3d135f389be2a42cacb0f9e7874b897ea4c9bb05d491c84828cbc84ec083e635d1cb3d9bd44e53d9d25af6eae47804b8b97052ff544eafd

test:
  secret_key_base: b2bb5b8537146c5d95fc3b6cf4eba503a4e8d2788935dd0ecb31d094a65a6d687c10b3703df1f9c0e162c52b48852b069389b24dea2f3f4413ab466250eea64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
